version: "3.5"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ct-daemon-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: ct-daemon-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: predictive-dialer-topic:1:1
    volumes:
      - ./resources/kafka/var/run/docker.sock:/var/run/docker.sock

  publisher:
    container_name: publisher
    image: predictive-dialer_publisher:0.0.0
    build:
      context: ./predictive-publisher
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ../predictive-publisher/:/usr/src/app
    ports:
      - 3000:3000
    restart: unless-stopped

  consumer_1:
    container_name: consumer1
    image: predictive-dialer_consumer:0.0.0
    environment:
      CONSUMER_NAME: consumer_1
    build:
      context: ./predictive-consumer
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ../predictive-publisher/:/usr/src/app
    restart: unless-stopped

  consumer_2:
    container_name: backend_2
    image: predictive-dialer_consumer:0.0.0
    environment:
      CONSUMER_NAME: consumer_2
    build:
      context: ./predictive-publisher
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ../predictive-publisher/:/usr/src/app
    restart: unless-stopped
